Repository oh930428/purplestone, pull requests merged in 2022-06, with the labels that each got.

#20 ✨ [feat] 반응형 기능 추가
  package-lock.json
  package.json
  src/assets/Images/process-card_03.png
  src/assets/Images/process-card_04.png
  src/assets/Images/process-card_05.png
  src/components/Header/Header.tsx
  src/pages/AllCoffees/AllCoffees.tsx
  src/pages/AllCoffees/components/MostPopularSection/DoughnutSection.tsx
  src/pages/AllCoffees/components/MostPopularSection/MostPopularSection.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/MakeCard/DrawSvg.tsx
  src/pages/Home/components/MakeCard/MakeCard.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/styles/mixin.ts
  src/types/doughnut.type.ts
  src/types/header.type.ts
  src/types/responsiveByDevice.type.ts
  yarn.lock
Labels: 🔨 - [ set ], 📦 - [ package ], ✨ - [ feat ], 🚚 - [ rename ]

#21 ✨ [feat] 반응형 기능 추가
  package-lock.json
  package.json
  src/assets/Images/process-card_03.png
  src/assets/Images/process-card_04.png
  src/assets/Images/process-card_05.png
  src/components/Header/Header.tsx
  src/pages/AllCoffees/AllCoffees.tsx
  src/pages/AllCoffees/components/MostPopularSection/DoughnutSection.tsx
  src/pages/AllCoffees/components/MostPopularSection/MostPopularSection.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/MakeCard/DrawSvg.tsx
  src/pages/Home/components/MakeCard/MakeCard.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/styles/mixin.ts
  src/types/doughnut.type.ts
  src/types/header.type.ts
  src/types/responsiveByDevice.type.ts
Labels: 🔨 - [ set ], 📦 - [ package ], ✨ - [ feat ], 🚚 - [ rename ]

#25 [feat] 쿠키 팝업 UI 및 기능 추가, 반응형 기능 추가
  src/assets/Images/popup-image.jpg
  src/components/Button/Button.tsx
  src/components/Card/UserCardSmall/UserCardSmall.tsx
  src/components/Card/UserCardSmall/UserCardSmallOption.tsx
  src/components/CookiePopup/CookiePopup.tsx
  src/components/Navigation/Navigation.tsx
  src/components/index.tsx
  src/pages/AllCoffees/components/UserCardListSection/UserCardListSection.tsx
  src/pages/CreateMyCard/CreateMyCard.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/styles/global.ts
  yarn.lock
Labels: ✨ - [ feat ], 💄 - [ design ]

#26 🐛 [fix] Home 페이지 OthersCoffee 세션 반응형 오류 수정
  src/pages/Home/Home.tsx
Labels: 🐛 - [ fix ]

#27 🔨 [set] Make a Card 세션 5번째 카드 height 값 삭제
  src/pages/Home/components/MakeCard/MakeCard.tsx
Labels: 🔨 - [ set ]

#28 [feat] 모바일 버튼 디자인 추가, 모바일 메뉴 기능 추가, 반응형 기능 추가(footer, userCardSmall)
  src/App.tsx
  src/components/Card/UserCardSmall/UserCardSmall.tsx
  src/components/Footer/Footer.tsx
  src/components/Navigation/Navigation.tsx
  src/pages/AllCoffees/components/UserCardListSection/UserCardListSection.tsx
  src/pages/CreateMyCard/CreateMyCard.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/styles/global.ts
Labels: ✨ - [ feat ], 💄 - [ design ]

#29 👷 [chore] 배포를 위한 json-server 설정 추가 및 쿠키팝업 버그 해결, 데이터 역순 정렬
  Procfile
  db.json
  package.json
  server.js
  src/components/Card/CardProcess/index.tsx
  src/components/Card/CardProfile/index.tsx
  src/components/Card/CardUser/UserCardOption.tsx
  src/components/Card/CardUser/index.tsx
  src/components/Card/CardUserSmall/UserOptionSmall.tsx
  src/components/Card/CardUserSmall/index.tsx
  src/components/CookiePopup/CookiePopup.tsx
  src/components/CookiePopup/index.tsx
  src/components/Footer/index.tsx
  src/components/index.tsx
  src/pages/AllCoffees/components/UserCardListSection/index.tsx
  src/pages/CreateMyCard/index.tsx
  src/pages/Home/components/Creators/index.tsx
  src/pages/Home/index.tsx
  src/properties/coffeDefaultOption.ts
  src/store/api/createMyCard.ts
  src/store/api/userCardList.ts
  src/store/api/userCardListPageParam.ts
  src/types/cardProfile.type.ts
  src/types/creators.types.ts
  src/types/profile.type.ts
Labels: 🐛 - [ fix ], 👷 - [ chore ], ✨ - [ feat ], 💄 - [ design ]

#30 🔨 [set] All coffees 페이지 The Most Popular 세션 Skeleton 적용
  src/components/Skeleton/SkeletonChart.tsx
  src/components/Skeleton/SkeletonHeader.tsx
  src/components/Skeleton/SkeletonProfileCard.tsx
  src/pages/AllCoffees/components/MostPopularSection/index.tsx
  src/pages/Home/components/Creators/index.tsx
  src/pages/Home/components/OthersCoffee/index.tsx
Labels: 🔨 - [ set ], 🚚 - [ rename ]

#31 🔨 [set] All coffees 페이지 The Most Popular 세션 Skeleton 적용
  src/components/Skeleton/SkeletonChart.tsx
  src/components/Skeleton/SkeletonHeader.tsx
  src/components/Skeleton/SkeletonProfileCard.tsx
  src/pages/AllCoffees/components/MostPopularSection/index.tsx
  src/pages/Home/components/Creators/index.tsx
  src/pages/Home/components/OthersCoffee/index.tsx
Labels: 🔨 - [ set ], 🚚 - [ rename ]

#32 🔨 [set] CreateMyCard 페이지 Skeleton 추가
  src/components/Skeleton/SkeletonCoffeeOption.tsx
  src/pages/CreateMyCard/index.tsx
Labels: 🔨 - [ set ]

#33 🔨 [set] CreateMyCard 페이지 Skeleton 추가
  src/components/Skeleton/SkeletonCoffeeOption.tsx
  src/pages/CreateMyCard/index.tsx
Labels: 🔨 - [ set ]

#34 🔨 [set] 캡처 사진 변경으로 인한 수정 사항
  db.json
  src/assets/Images/coffee-card-image1.png
  src/assets/Images/coffee-card-image2.png
  src/assets/Images/coffee-card-image3.png
  src/assets/Images/coffee-card-image4.png
  src/assets/Images/coffee-card-image5.png
  src/assets/Images/coffee-card-image6.png
  src/assets/Images/coffee-card-image7.png
  src/assets/Images/process-card1.png
  src/assets/Images/process-card2.png
  src/assets/Images/process-card3.png
  src/assets/Images/process-card4.png
  src/assets/Images/process-card5.png
  src/assets/Images/process-card_01.png
  src/assets/Images/process-card_02.png
  src/assets/Images/process-card_03.png
  src/assets/Images/process-card_04.png
  src/assets/Images/process-card_05.png
  src/pages/Home/components/MakeCard/DrawSvg.tsx
  src/pages/Home/components/MakeCard/index.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/styles/mixin.ts
Labels: 🔨 - [ set ]

#35 [feat] createMyCard 캡쳐 기능 추가, 모바일 메뉴 디자인 수정,
  package.json
  src/components/Card/CardUser/UserCardOption.tsx
  src/components/Card/CardUser/index.tsx
  src/components/Footer/index.tsx
  src/components/Navigation/index.tsx
  src/hooks/useFetch.ts
  src/pages/AllCoffees/components/UserCardListSection/index.tsx
  src/pages/CreateMyCard/index.tsx
  src/styles/mixin.ts
  yarn.lock
Labels: ✨ - [ feat ], 💡- [ comment ], 💄 - [ design ]

#36 [fix] CreateMyCard 페이지에서 캡쳐시 텍스트가 잘려나오는 버그 수정
  package-lock.json
  package.json
  src/pages/CreateMyCard/index.tsx
Labels: 🐛 - [ fix ]

#37 🚚 [rename] CoffeeOptionSection , chooseCoffeeOption 파일명 수정
  db.json
  src/components/Card/CardProcess/index.tsx
  src/components/Card/CardUser/index.tsx
  src/components/Footer/index.tsx
  src/components/Loader/index.tsx
  src/pages/CreateMyCard/components/CategorySection/Category.tsx
  src/pages/CreateMyCard/components/CategorySection/index.tsx
  src/pages/CreateMyCard/components/index.tsx
  src/store/api/createMyCard.ts
  src/types/createMyCard.type.ts
  yarn.lock
Labels: 🚚 - [ rename ]
