Repository oh930428/purplestone, pull requests merged in 2022-05, with the labels that each got.

#1 Feature/store setup
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/models/example.model.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/store/api/exampleApi.ts
  src/store/hook.ts
  src/store/index.ts
  tsconfig.json
  yarn.lock
Labels: 📦 - [ package ]

#2 [feat] 디자인 시스템 추가 및 필요 라이브러리 추가, page Router 연결, MainPage UI 추가(Navigation, Footer, Button, social-icon, HeaderSection, Creators Section(ProfileCard , Header)), Creators Section -> mock 데이터 사용 데이터 패칭
  .prettierrc
  README.md
  db.json
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/Icons/socials/facebook.png
  src/assets/Icons/socials/google.png
  src/assets/Icons/socials/instagram.png
  src/assets/Images/bg-profile_01.png
  src/assets/Images/bg-profile_02.png
  src/assets/Images/bg-profile_03.png
  src/assets/Images/bg-section.jpg
  src/assets/Images/card-image.png
  src/assets/Images/profile_01.png
  src/assets/Images/profile_02.png
  src/assets/Images/profile_03.png
  src/components/Button/Button.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Icon/IconSocial.tsx
  src/components/Navigation/Navigation.tsx
  src/components/index.tsx
  src/hooks/useMouseEffect.tsx
  src/hooks/useWindowSize.tsx
  src/pages/AllCoffes/AllCoffes.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/Creators/Confetti.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/pages/Home/components/index.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/index.tsx
  src/store/api/creators.ts
  src/store/api/exampleApi.ts
  src/store/index.ts
  src/styles/colors.ts
  src/styles/font.ts
  src/styles/global.ts
  src/styles/index.ts
  src/styles/mixin.ts
  src/types/button.types.ts
  src/types/creators.types.ts
  src/types/example.types.ts
  src/types/header.types.ts
  src/types/iconSocial.type.ts
  src/types/profileCard.type.ts
  tsconfig.json
  yarn.lock
Labels: ✨ - [ feat ]

#3 📦 [package] 누락된 라이브러리 추가 (json-server)
  package-lock.json
  package.json
  yarn.lock
Labels: 📦 - [ package ]

#4 [design] global font-size 설정, max-width 수정
  src/components/Navigation/Navigation.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/styles/global.ts
  src/styles/mixin.ts
Labels: 💄 - [ design ]

#5 ✨ [feat] otherscoffee 세션 UI 개발 및 otherscoffee 세션의 card 커버플로우 기능 추가
  .prettierrc
  db.json
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/Icons/socials/facebook.png
  src/assets/Icons/socials/google.png
  src/assets/Icons/socials/instagram.png
  src/assets/Images/bg-profile_01.png
  src/assets/Images/bg-profile_02.png
  src/assets/Images/bg-profile_03.png
  src/assets/Images/bg-section.jpg
  src/assets/Images/card-image.png
  src/assets/Images/coffee-card-image.png
  src/assets/Images/profile_01.png
  src/assets/Images/profile_02.png
  src/assets/Images/profile_03.png
  src/components/Button/Button.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Icon/IconSocial.tsx
  src/components/Navigation/Navigation.tsx
  src/components/index.tsx
  src/hooks/useMouseEffect.tsx
  src/hooks/useWindowSize.tsx
  src/pages/AllCoffes/AllCoffes.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/Creators/Confetti.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/pages/Home/components/index.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/index.tsx
  src/store/api/creators.ts
  src/store/api/exampleApi.ts
  src/store/api/otherscoffee.ts
  src/store/index.ts
  src/styles/colors.ts
  src/styles/font.ts
  src/styles/global.ts
  src/styles/index.ts
  src/styles/mixin.ts
  src/types/button.types.ts
  src/types/creators.types.ts
  src/types/example.types.ts
  src/types/header.types.ts
  src/types/iconSocial.type.ts
  src/types/othersCoffee.type.ts
  src/types/profileCard.type.ts
  tsconfig.json
  yarn.lock
Labels: 📦 - [ package ], ✨ - [ feat ]

#6 ✨ [feat] otherscoffee 세션 UI 개발 및 otherscoffee 세션의 card 커버플로우 기능 추가
  db.json
  package-lock.json
  package.json
  src/assets/Images/coffee-card-image.png
  src/pages/Home/Home.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/pages/Home/components/index.tsx
  src/store/api/otherscoffee.ts
  src/store/index.ts
  src/types/othersCoffee.type.ts
  yarn.lock
Labels: 📦 - [ package ], ✨ - [ feat ]

#7 [feat] Footer 디자인 수정, MyCard 페이지 UI 및 기능 추가
  db.json
  src/assets/Icons/beans/colombiaSupremo.png
  src/assets/Icons/beans/ethiopiaYirgacheffee.png
  src/assets/Icons/beans/guatemalaAntiguaSHB.png
  src/assets/Icons/beans/jamaicaBlueMountain.png
  src/assets/Icons/beans/kenyaAA.png
  src/assets/Icons/beans/tanzaniaAA.png
  src/assets/Icons/bottles/cup-disposable.png
  src/assets/Icons/bottles/cup-mug.png
  src/assets/Icons/bottles/cup-reuseable.png
  src/assets/Icons/bottles/cup-takeout-hot.png
  src/assets/Icons/bottles/cup-tea.png
  src/assets/Icons/bottles/cup-tumbler.png
  src/assets/Icons/brands/coffeebean.png
  src/assets/Icons/brands/ediya.png
  src/assets/Icons/brands/hollys.png
  src/assets/Icons/brands/pascucci.png
  src/assets/Icons/brands/starbucks.png
  src/assets/Icons/brands/twosome.png
  src/assets/Icons/coffeetypes/americano.png
  src/assets/Icons/coffeetypes/americano2.png
  src/assets/Icons/coffeetypes/caffelatte.png
  src/assets/Icons/coffeetypes/caffelatte2.png
  src/assets/Icons/coffeetypes/caffemocha.png
  src/assets/Icons/coffeetypes/caffemocha2.png
  src/assets/Icons/coffeetypes/cappuccino.png
  src/assets/Icons/coffeetypes/cappuccino2.png
  src/assets/Icons/coffeetypes/espresso.png
  src/assets/Icons/coffeetypes/espresso2.png
  src/assets/Icons/coffeetypes/macchiato.png
  src/assets/Icons/coffeetypes/macchiato2.png
  src/assets/Icons/temperature/half.png
  src/assets/Icons/temperature/hot.png
  src/assets/Icons/temperature/ice.png
  src/assets/Images/bg-card-small.png
  src/assets/Images/bg-card.png
  src/assets/Images/bg-circle-active.png
  src/assets/Images/bg-circle.png
  src/assets/Images/bg-digram-small.png
  src/assets/Images/bg-digram.png
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/CoffeeOption/CoffeeOption.tsx
  src/components/Footer/Footer.tsx
  src/components/index.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/MyCard/components/CoffeeOptionSection.tsx
  src/pages/MyCard/components/index.tsx
  src/store/api/myCard.ts
  src/styles/font.ts
  src/types/myCard.types.ts
Labels: ✨ - [ feat ], 💄 - [ design ], 🚚 - [ rename ]

#10 🔨 [set] myCardApi 추가
  src/store/index.ts
Labels: 🔨 - [ set ]

#11 ✨ [feat] Skeleton UI 개발
  src/components/Skeleton/HeaderSkeleton.tsx
  src/components/Skeleton/ProfileCardSkeleton.tsx
  src/components/Skeleton/Skeleton.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/types/skeleton.types.ts
Labels: ✨ - [ feat ]

#12 ✨ [feat] Skeleton UI 개발
  src/components/Skeleton/HeaderSkeleton.tsx
  src/components/Skeleton/ProfileCardSkeleton.tsx
  src/components/Skeleton/Skeleton.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/Home/components/OthersCoffee/OthersCoffee.tsx
  src/types/skeleton.types.ts
Labels: ✨ - [ feat ]

#13 🔨 [set] 이미지 수정으로 인한 값 수정
  src/assets/Images/process-card_01.png
  src/assets/Images/process-card_02.png
  src/assets/Images/process-card_03.png
  src/assets/Images/process-card_04.png
  src/assets/Images/process-card_05.png
  src/pages/Home/components/MakeCard/MakeCard.tsx
Labels: 🔨 - [ set ], 💄 - [ design ]

#14 🐛[fix] 커피 옵션 선택하면, 이전에 선택한 옵션이 초기화 되는 버그 수정
  db.json
  public/index.html
  src/components/Button/Button.tsx
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/MakeMyCard/MakeMyCardOption.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/CoffeeOption/CoffeeOption.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/index.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/MyCard/components/CoffeeOptionSection.tsx
  src/store/api/myCard.ts
  src/store/hook.ts
  src/store/index.ts
  src/store/state/MyCardSlice.ts
  src/styles/font.ts
  src/types/myCard.types.ts
  yarn.lock
Labels: 🐛 - [ fix ], 💄 - [ design ]

#15 ✨ [feat] index store 누락 추가
  src/store/index.ts
Labels: ✨ - [ feat ]

#16 [feat] 선택한 커피 옵션 상태관리 / AllCoffees 페이지 / UserCardList 컴포넌트 추가
  db.json
  src/App.tsx
  src/components/Button/Button.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Card/UserCard/UserCard.tsx
  src/components/Card/UserCard/UserCardOption.tsx
  src/components/Card/UserCardSmall/UserCardSmall.tsx
  src/components/Card/UserCardSmall/UserCardSmallOption.tsx
  src/components/ChooseCoffeeOption/ChooseCoffeeOption.tsx
  src/components/Header/Header.tsx
  src/components/Icon/IconSocial.tsx
  src/components/Icon/IconsCoffeeOption.tsx
  src/components/Navigation/Navigation.tsx
  src/components/index.tsx
  src/pages/AllCoffees/AllCoffees.tsx
  src/pages/AllCoffees/components/UserCardListSection/UserCardListSection.tsx
  src/pages/AllCoffees/components/index.tsx
  src/pages/AllCoffes/AllCoffes.tsx
  src/pages/CreateMyCard/CreateMyCard.tsx
  src/pages/CreateMyCard/components/CoffeeOptionSection.tsx
  src/pages/CreateMyCard/components/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/MakeCard/MakeCard.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/MyCard/components/CoffeeOptionSection.tsx
  src/pages/index.tsx
  src/store/api/createMyCard.ts
  src/store/api/exampleApi.ts
  src/store/api/myCard.ts
  src/store/api/userCardList.ts
  src/store/index.ts
  src/store/state/MyCardSlice.ts
  src/types/button.type.ts
  src/types/createMyCard.ts
  src/types/example.type.ts
  src/types/header.type.ts
  src/types/myCard.types.ts
  src/types/userCardSmall.ts
Labels: ✨ - [ feat ], 🚚 - [ rename ]

#17 ✨ [feat] The Most Popular UI 개발 및 DB 추가
  db.json
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Button/Button.tsx
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Card/UserCard/UserCard.tsx
  src/components/Card/UserCard/UserCardOption.tsx
  src/components/Card/UserCardSmall/UserCardSmall.tsx
  src/components/Card/UserCardSmall/UserCardSmallOption.tsx
  src/components/ChooseCoffeeOption/ChooseCoffeeOption.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Icon/IconSocial.tsx
  src/components/Icon/IconsCoffeeOption.tsx
  src/components/Navigation/Navigation.tsx
  src/components/index.tsx
  src/pages/AllCoffees/AllCoffees.tsx
  src/pages/AllCoffees/components/MostPopularSection/DoughnutSection.tsx
  src/pages/AllCoffees/components/MostPopularSection/MostPopularSection.tsx
  src/pages/AllCoffees/components/UserCardListSection/UserCardListSection.tsx
  src/pages/AllCoffees/components/index.tsx
  src/pages/AllCoffes/AllCoffes.tsx
  src/pages/CreateMyCard/CreateMyCard.tsx
  src/pages/CreateMyCard/components/CoffeeOptionSection.tsx
  src/pages/CreateMyCard/components/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/Creators/Creators.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/pages/Home/components/MakeCard/MakeCard.tsx
  src/pages/Home/components/OthersCoffee/CoverflowSection.tsx
  src/pages/MyCard/MyCard.tsx
  src/pages/MyCard/components/CoffeeOptionSection.tsx
  src/pages/index.tsx
  src/store/api/createMyCard.ts
  src/store/api/exampleApi.ts
  src/store/api/mostPopular.ts
  src/store/api/myCard.ts
  src/store/api/userCardList.ts
  src/store/hook.ts
  src/store/index.ts
  src/store/state/MyCardSlice.ts
  src/styles/font.ts
  src/types/button.type.ts
  src/types/createMyCard.ts
  src/types/doughnut.type.ts
  src/types/example.type.ts
  src/types/header.type.ts
  src/types/myCard.types.ts
  src/types/userCardSmall.ts
  yarn.lock
Labels: 🐛 - [ fix ], 📦 - [ package ], ✨ - [ feat ]

#18 ✨ [feat] The Most Popular UI 개발 및 DB 추가
  db.json
  package-lock.json
  package.json
  src/App.tsx
  src/pages/AllCoffees/AllCoffees.tsx
  src/pages/AllCoffees/components/MostPopularSection/DoughnutSection.tsx
  src/pages/AllCoffees/components/MostPopularSection/MostPopularSection.tsx
  src/pages/AllCoffees/components/index.tsx
  src/store/api/mostPopular.ts
  src/store/index.ts
  src/types/doughnut.type.ts
  yarn.lock
Labels: 🐛 - [ fix ], 📦 - [ package ], ✨ - [ feat ]

#19 [feat] All Coffees 페이지: 무한 스크롤 기능 추가, CreateMyCard 페이지: 게시하기 버튼 클릭시 컨펌창 띄우기 기능 추가
  db.json
  package.json
  src/App.tsx
  src/assets/Icons/coffeetypes/americano2.png
  src/assets/Icons/coffeetypes/caffelatte2.png
  src/assets/Icons/coffeetypes/caffemocha2.png
  src/assets/Icons/coffeetypes/cappuccino2.png
  src/assets/Icons/coffeetypes/espresso2.png
  src/assets/Icons/coffeetypes/macchiato2.png
  src/components/Card/UserCardSmall/UserCardSmall.tsx
  src/components/Loader/Loader.tsx
  src/components/index.tsx
  src/hooks/useFetch.ts
  src/index.tsx
  src/pages/AllCoffees/components/UserCardListSection/UserCardListSection.tsx
  src/pages/CreateMyCard/CreateMyCard.tsx
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/store/api/userCardListPageParam.ts
  src/types/button.type.ts
  yarn.lock
Labels: 🐛 - [ fix ], ✨ - [ feat ]
